services:
  db:
    image: postgres:13
    env_file:
      - ./database/config/.env
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - shop_network

  product:
    build: ./product
    ports:
      - "8001:8001"
    depends_on:
      - db
    networks:
      - shop_network

  auth:
    build:
      dockerfile: ./Dockerfile
      context: ./auth
    env_file:
      - environment/.auth.env
    depends_on:
      - db
    networks:
      - shop_network

  cart:
    build: ./cart
    ports:
      - "8003:8003"
    depends_on:
      - db
      - auth
    env_file:
      - ./cart/.env
    networks:
      - shop_network

  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - product
      - auth
    networks:
      - shop_network

volumes:
  db_data:

networks:
  shop_network:
    driver: bridge