services:
  database-postgres:
    image: postgres:14
    container_name: db
    environment:
      POSTGRES_USER: konstantin
      POSTGRES_PASSWORD: konstantin
      POSTGRES_DB: user
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - shop-network

  backend-authentication:
    build:
      context: ./backend
      dockerfile: /auth/Dockerfile
    container_name: backend
    env_file:
      - backend/auth/.env
    ports:
      - "8000:8000"
    depends_on:
      - database-postgres
    restart: on-failure
    networks:
      - shop-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"  # Внутренний порт приложения
    depends_on:
      - backend-authentication
    networks:
      - shop-network


  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8004:80"
    depends_on:
      - frontend
      - backend-authentication
      - database-postgres
    networks:
      - shop-network

volumes:
  db_data:

networks:
  shop-network:
    driver: bridge
