from src.config.env import StrEnv, IntEnv, StrListEnv

__all__ = [
    "DATABASE_HOST",
    "DATABASE_PORT",
    "DATABASE_NAME",
    "DATABASE_USER",
    "DATABASE_PASSWORD",
    "SECRET_KEY",
    "ALGORITHM",
    "ACCESS_TOKEN_EXPIRE_MINUTES",
    "HTTP_HOST",
    "HTTP_PORT",
    "PROJECT_NAME",
    "DOCS_URL",
    "OPENAPI_URL",
    "ORIGIN_URLS"
]

DATABASE_HOST: str = StrEnv("POSTGRES_HOST")
DATABASE_PORT: str = StrEnv("POSTGRES_PORT")
DATABASE_NAME: str = StrEnv("POSTGRES_NAME")
DATABASE_USER: str = StrEnv("POSTGRES_USER")
DATABASE_PASSWORD: str = StrEnv("POSTGRES_PASSWORD")
SECRET_KEY: str = StrEnv("AUTH_SECRET_KEY")
ALGORITHM: str = StrEnv("AUTH_ALGORITHM")
ACCESS_TOKEN_EXPIRE_MINUTES: int = IntEnv("AUTH_ACCESS_TOKEN_EXPIRE_MINUTES")

HTTP_HOST: str = StrEnv("AUTH_HTTP_HOST")
HTTP_PORT: int = IntEnv("AUTH_HTTP_PORT")

PROJECT_NAME: str = StrEnv("AUTH_PROJECT_NAME")
DOCS_URL: str = StrEnv("AUTH_DOCS_URL")
OPENAPI_URL: str = StrEnv("AUTH_OPENAPI_URL")

ORIGIN_URLS: list = StrListEnv("ORIGIN_URLS")